### ISSUE TITLE
AttributeError: 'module' object has no attribute 'pbkdf2_hmac'

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-server#66]
Auth not working because of the above error in `auth.py` @afischer

**Comment by adelq** [comment]
Reason: server has Python 2.7.6, `pbkdf2_hmac` was introduced in 2.7.8

**Comment by afischer** [comment]
Will upgrade!
@adelq please send me a gist with the code you are using to test SSO as well!

**Comment by adelq** [comment]
At the moment, I'm simply accessing https://api.pennlabs.org/auth because that is how it will be accessed by the mobile clients.

**Comment by afischer** [comment]
Ah, ok. So you're just running the mobile server locally to see errors, or are you checking the logs on the server?

-- 
Andrew Fischer


On December 5, 2015 at 9:14:53 PM, Adel Qalieh (notifications@github.com) wrote:

At the moment, I'm simply accessing https://api.pennlabs.org/auth because that is how it will be accessed by the mobile clients.

**Comment by adelq** [comment]
The latter, I'm checking the logs on the server since you can't do any form of auth testing locally ATM.

**Comment by afischer** [comment]
Fixed with server side updates

**Comment by adelq** [comment]
For future reference: `add-apt-repository ppa:fkrull/deadsnakes-python2.7 && apt-get update && apt-get upgrade -y`
